describe('Automatic Order Billing - Positive Case', () => {
  const orderId = '12345';
  const customerId = 'CUST001';
  const orderItems = ['Product A', 'Product B'];
  const billingAddress = '123 Main St, City, Country';

  before(() => {
    cy.login();
    cy.visit('/order-management');
  });

  it('should navigate to the Order Management module', () => {
    cy.url().should('include', '/order-management');
  });

  it('should select the order with ID 12345', () => {
    cy.get(`[data-test=order-id-${orderId}]`).click();
    cy.get('.order-details').should('contain', orderId);
  });

  it('should verify the order items and customer information', () => {
    cy.get('.customer-id').should('contain', customerId);
    cy.get('.order-items').should('contain', orderItems[0]).and('contain', orderItems[1]);
  });

  it('should initiate the automatic billing process', () => {
    cy.get('.initiate-billing').click();
    cy.get('.billing-process').should('not.contain', 'error');
  });

  it('should check the billing details generated by the system', () => {
    cy.get('.billing-details').should('contain', billingAddress);
  });

  it('should verify that the billing charges are correctly applied', () => {
    cy.get('.billing-charges').should('contain', 'calculated and applied');
  });

  it('should check the order status after billing', () => {
    cy.get('.order-status').should('contain', 'Billed');
  });

  it('should verify that the billing details are stored in the system', () => {
    cy.get('.order-history').should('contain', 'Billing details saved');
  });

  it('should ensure a billing confirmation email is sent', () => {
    cy.get('.email-confirmation').should('contain', 'sent');
  });

  it('should verify the email content for correctness', () => {
    cy.get('.email-content').should('contain', 'correct billing details').and('contain', 'customer information');
  });

  it('should review the audit logs for the billing process', () => {
    cy.get('.audit-logs').should('contain', 'detailed steps');
  });

  it('should check for any error messages in the system logs', () => {
    cy.get('.system-logs').should('not.contain', 'error');
  });

  it('should verify the integration with the payment gateway', () => {
    cy.get('.payment-gateway').should('contain', 'seamless');
  });

  it('should test the system performance during the billing process', () => {
    cy.get('.system-performance').should('contain', 'efficient');
  });

  it('should ensure the billing process can handle multiple orders', () => {
    cy.get('.multiple-orders').should('contain', 'processed without errors');
  });
});