Feature: Logging Failed Sign-In Attempts for Auditing
Scenario: Verify system logs failed sign-in attempt for auditing purposes
Given access to the system's logging and auditing tools
When I attempt to log in to the application using invalid credentials
Then the login attempt fails and an error message is displayed
Scenario: Access the system's logging interface
Given access to the application and its logging system
When I access the system's logging interface to view recent logs
Then the logging interface is accessed successfully
Scenario: Search for entries related to the failed sign-in attempt
When I search for entries related to the failed sign-in attempt
Then an entry for the failed sign-in attempt is found in the logs
Scenario: Verify log entry details
When I verify the log entry includes the timestamp of the failed attempt
Then the log entry includes the correct timestamp
When I check that the log entry contains the username used in the failed attempt
Then the username is correctly logged in the entry
When I ensure that the log entry includes the IP address of the device used
Then the IP address is accurately recorded in the log
When I verify that the log entry specifies the reason for the failed attempt (e.g., incorrect password)
Then the reason for the failure is clearly stated in the log
Scenario: Security and accessibility of log entry
When I check if the log entry is stored in a secure and tamper-proof manner
Then the log entry is stored securely and cannot be altered
When I validate that the log entry is accessible to authorized personnel only
Then only authorized users can access the log entry
Scenario: Retention and reporting of log entry
When I ensure the log entry is retained for the appropriate duration as per company policy
Then the log entry retention period complies with company policy
When I check if the log entry is included in audit reports generated by the system
Then the log entry is present in the audit reports
Scenario: Alert system for multiple failed attempts
When I verify that the logging system sends an alert to the security team for multiple failed attempts
Then the security team receives an alert for repeated failed attempts
Scenario: Consistency and performance under load
When I ensure that the log entry is formatted consistently with other entries
Then the log entry follows the same format as other entries
When I test the system's ability to log failed attempts under high load conditions
Then failed attempts are logged correctly even under high load
Scenario: Recovery after system restart
When I confirm that the logging system can recover and retain entries after a system restart
Then log entries are retained and accessible after a system restart