Feature: Validate system behavior when email dispatch fails for ZPB1 output

  @TC-126
  Scenario: User logs into the SAP system with valid credentials
    Given user navigates to the SAP login page
    When user enters valid credentials
    Then user is successfully logged into the SAP system

  @TC-126
  Scenario: User navigates to the periodic billing document processing transaction
    Given user is logged into the SAP system
    When user navigates to the periodic billing document processing transaction
    Then the periodic billing document processing screen is displayed

  @TC-126
  Scenario Outline: User processes ZFR document and verifies ZPB1 output generation and email dispatch failure
    Given user is on the periodic billing document processing screen
      And output determination for ZPB1 is configured and active
      And email notification settings are misconfigured or email server connectivity is disabled
    When user enters the ZFR document ID "<ZFR_Document_ID>" in the input field
      And user triggers the output processing for the selected ZFR document
    Then the system generates the ZPB1 output for the ZFR document
      And the ZPB1 output is successfully attached to the ZFR document
    When user navigates to the email dispatch logs in the system
    Then the email dispatch logs are displayed
    When user searches for the email dispatch entry for the ZPB1 output
    Then no email dispatch entry is found or an error entry is logged
    When user reviews the error message generated by the system for the email dispatch failure
    Then the error message provides detailed information about the cause of the email dispatch failure
    When user checks the system logs for additional details about the email dispatch failure
    Then the system logs contain detailed information about the email dispatch failure
    When user verifies that the system retains the ZPB1 output for the ZFR document despite the email dispatch failure
    Then the ZPB1 output is retained and can be accessed in the system

    Examples:
      | ZFR_Document_ID |
      | ZFR67890        |

  @TC-126
  Scenario Outline: User resends email after correcting email settings and verifies successful dispatch
    Given the email dispatch failure for ZPB1 output has been logged
      And user has corrected the email settings
    When user attempts to resend the email
    Then the email is successfully resent
      And the dispatch logs are updated
    When user verifies the email content
    Then the email contains the correct ZPB1 attachment and details

    Examples:
      | ZFR_Document_ID |
      | ZFR67890        |